using System;

namespace APItoDB_WAMIS.A_Models
{
    public class ASOS_WeatherData
    {
        public string TM { get; set; }
        public int? WD { get; set; }
        public float? GST_WD { get; set; }
        public float? GST_TM { get; set; }
        public float? PS { get; set; }
        public float? PR { get; set; }
        public float? TD { get; set; }
        public float? PV { get; set; }
        public float? RN_DAY { get; set; }
        public float? SD_HR3 { get; set; }
        public float? SD_TOT { get; set; }
        public float? WP { get; set; }
        public float? CA_TOT { get; set; }
        public float? CH_MIN { get; set; }
        public float? CT_TOP { get; set; }
        public float? CT_LOW { get; set; }
        public float? SI { get; set; }
        public float? TS { get; set; }
        public float? TE_01 { get; set; }
        public float? TE_03 { get; set; }
        public float? WH { get; set; }
        public float? IR { get; set; }
        public float? RN_JUN { get; set; }
        public float? WR_DAY { get; set; }
        public float? WS_MAX { get; set; }
        public float? WD_INS { get; set; }
        public float? WS_INS_TM { get; set; }
        public float? TA_MAX { get; set; }
        public float? TA_MIN { get; set; }
        public float? TD_AVG { get; set; }
        public float? TG_MIN { get; set; }
        public float? HM_MIN { get; set; }
        public float? PV_AVG { get; set; }
        public float? EV_L { get; set; }
        public float? PA_AVG { get; set; }
        public float? PS_MAX { get; set; }
        public float? PS_MIN { get; set; }
        public float? SS_DAY { get; set; }
        public float? SS_CMB { get; set; }
        public float? RN_D99 { get; set; }
        public float? SD_NEW { get; set; }
        public float? SD_MAX { get; set; }
        public float? TE_05 { get; set; }
        public float? TE_15 { get; set; }
        public float? TE_50 { get; set; }
        public float? TMST { get; set; }
        public float? DTM { get; set; }
        public float? DIR { get; set; }
        public float? LAT { get; set; }
        public float? VAL { get; set; }
        public float? STN { get; set; }
        public float? WS { get; set; }
        public float? GST_WS { get; set; }
        public float? PA { get; set; }
        public float? PT { get; set; }
        public float? TA { get; set; }
        public float? HM { get; set; }
        public float? RN { get; set; }
        public float? RN_INT { get; set; }
        public float? SD_DAY { get; set; }
        public float? WC { get; set; }
        public float? WW { get; set; }
        public float? CA_MID { get; set; }
        public float? CT { get; set; }
        public float? CT_MID { get; set; }
        public float? SS { get; set; }
        public float? ST_GD { get; set; }
        public float? TE_005 { get; set; }
        public float? TE_02 { get; set; }
        public float? ST_SEA { get; set; }
        public float? BF { get; set; }
        public float? IX { get; set; }
        public float? WS_AVG { get; set; }
        public float? WD_MAX { get; set; }
        public float? WS_MAX_TM { get; set; }
        public float? WS_INS { get; set; }
        public float? TA_AVG { get; set; }
        public float? TA_MAX_TM { get; set; }
        public float? TA_MIN_TM { get; set; }
        public float? TS_AVG { get; set; }
        public float? HM_AVG { get; set; }
        public float? HM_MIN_TM { get; set; }
        public float? EV_S { get; set; }
        public float? FG_DUR { get; set; }
        public float? PS_AVG { get; set; }
        public float? PS_MAX_TM { get; set; }
        public float? PS_MIN_TM { get; set; }
        public float? SS_DUR { get; set; }
        public float? SI_DAY { get; set; }
        public float? RN_DUR { get; set; }
        public float? SD_NEW_TM { get; set; }
        public float? SD_MAX_TM { get; set; }
        public float? TE_10 { get; set; }
        public float? TE_30 { get; set; }
        public float? S { get; set; }
        public float? TMED { get; set; }
        public float? ST { get; set; }
        public float? LON { get; set; }
        public float? HT { get; set; }
    }
}